name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build . --file Dockerfile --tag genai_app_acitions:$(date +%s)

        # Run the Docker container locally
        docker run -d -p 3000:3000 genai_app_acitions:$(date +%s)
      continue-on-error: true
